In [1]:
import numpy as np

In [2]:
print(np.__version__)  #Checking Numpy Version

1.19.2


In [3]:
arr = np.array([1,2,3,4,5])  # 1-D Arrays
print(arr)

[1 2 3 4 5]


In [4]:
print(type(arr)) #built-in Python function tells us the type of the object passed to it.

<class 'numpy.ndarray'>


In [5]:
arr2 = np.array([[1, 2, 3], [4, 5, 6]])    #2D

print(arr2) 

[[1 2 3]
 [4 5 6]]


In [6]:
arr3 = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]]) #Create a 3-D array with two 2-D arrays
print(arr3)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [8]:
print(arr.ndim)  #Check Number of Dimensions
print(arr2.ndim)
print(arr3.ndim)

1
2
3


## Access Array Elements

In [9]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([[1, 2, 3], [4, 5, 6]])
print(a[0] + a[3])

5


In [10]:
print(b[0,2])

3


In [11]:
# Negative Indexing
print(a[-2])
print(b[-1,-2])

4
5


## Slicing arrays

In [12]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

In [13]:
print(arr[1:5])
print(arr[1:])

[2 3 4 5]
[2 3 4 5 6 7]


In [14]:
print(arr[1:5:2])    #Skip two value from index 1 to 5

[2 4]


## Datatype of array

In [15]:
a.dtype
b.dtype

dtype('int32')

In [16]:
arr.dtype

dtype('int32')